version: '3.8'

services:
  backend:
    image: bayajid23/scalable-todo-server:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    image: bayajid23/scalable-todo-client:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped